### ISSUE TITLE
NGINX: Why 302 redirect for SSL? 

### ISSUE THREAD

**Issue by krishamoud** [ehazlett/interlock#185]
If `SSLOnly` is turned on then wouldn't a 301 be correct as it's a permanent move?  This does't have any effect on my setup but I have been googling trying to figure out the differences between the two.  The only reason people seem to care about it is because of SEO.  This was the only thing I could find from google about SEO.

https://support.google.com/webmasters/answer/6073543?hl=en

**Comment by mbentley** [comment]
The reason about 302 instead of 301 came from https://github.com/ehazlett/interlock/pull/51.  With Interlock being about dynamic load balancing, what happens if configuration changes when you previously had an endpoint that redirected to SSL with a 301 but not longer want to force SSL?  Browsers may/more than likely will cache a 301 where as a 302 should not be cached.

**Comment by krishamoud** [comment]
I see.  Thanks for the information!
