### ISSUE TITLE
[Feature] Add option to disable the automatic restart of the haproxy container

### ISSUE THREAD

**Issue by goetas** [ehazlett/interlock#190]
I'm using HAProxy and the restart of the container creates a downtime of 1-2s (due to the container restart).

Currently HAProxy using the option `-sf` allows some kind of configuration refresh.. that makes useless the container restart.

(I'm using an approach similar to https://github.com/million12/docker-haproxy to detect configurarion file changes)

Having this feature allows to have almost no downtime when containers are added/removed

**Comment by ehazlett** [comment]
We used to do this when HAProxy was embedded.  Since we moved to use external proxy images we can no longer control the life cycle of the container to that level.  We could look at possibly allowing Interlock to manage launching the proxy containers as an alternative that would allow control over how HAProxy is started.

In an ideal world, HAProxy should be able to handle a `SIGHUP` and "just work" like nginx does.  Then we could do the same thing we use for nginx instead of this reload hassle.

**Comment by goetas** [comment]
currently im using this bug https://github.com/ehazlett/interlock/issues/189 to achieve the feature :smile:

**Comment by goetas** [comment]
> We used to do this when HAProxy was embedded. Since we moved to use external proxy images we can no longer control the life cycle of the container to that level.

currently i'm using a custom image of haproxy... of course handling signals is cool but adding an option to the extension as example "DoNotRestartContainer=1" will allow users to do their implementation of the restart policy

Adding a simple "exit" in https://github.com/ehazlett/interlock/blob/master/ext/lb/haproxy/haproxy.go#L66 will be enough

```
[[Extensions]]
Name = "haproxy"
ConfigPath = "/usr/local/etc/haproxy/haproxy.cfg"
PidPath = "/var/run/haproxy.pid"
TemplatePath = "/usr/local/haproxy.cfg.template"
BackendOverrideAddress = "172.17.0.1"
MaxConn = 1024
Port = 80
AdminUser = "admin"
AdminPass = "interlock"
DoNotRestartContainer=1
```

**Comment by goetas** [comment]
https://gist.github.com/goetas/8a6c95b7fc0d25f2e866db385fee467a is my modified version of the official HAProxy

**Comment by goetas** [comment]
Using docker gen, offers similar and more powerful features
