### ISSUE TITLE
Scaling Interlock

### ISSUE THREAD

**Issue by primehaxor** [ehazlett/interlock#194]
Hi, im have a ucp running and i would like to know when i want a HA thinking if i lose some node i have to deploy one interlock for each node on my cluster... the problem is i can't set the environment constraint with interlock configs...

this is my current compose, but i cant use interlock with volume, it can't find the config.toml

interlock:
    image: ehazlett/interlock:master
    command: run -c /etc/interlock/config.toml
    tty: true
    ports:
        - 8080
    environment:
       - "constraint:node==worker01"
    volumes:
        - ucp-node-certs:/certs
        - interlock-config:/etc/interlock
    restart: always

nginx:
    image: nginx:latest
    entrypoint: nginx
    command: -g "daemon off;" -c /etc/nginx/nginx.conf
    ports:
        - 80
    labels:
        - "interlock.ext.name=nginx"
    restart: always
    environment:
      - "constraint:node==worker01"

app:
    image: ehazlett/docker-demo:latest
    ports:
        - 8080
    labels:
        - "interlock.hostname=test"
        - "interlock.domain=local"
    environment:
        - "constraint:node==worker01"

but the file exists...

shell#/var/lib/docker/volumes/interlock-config/_data# ls
config.toml

When i try to scale the application sometimes interlock starts on the same node..

the example below works but i cant choose which node should starts... there's a way to use the INTERLOCK_CONFIG with constraint?

interlock:
    image: ehazlett/interlock:master
    command: -D run
    tty: true
    ports:
        - 8080
    environment:
        INTERLOCK_CONFIG: |
            ListenAddr = ":8080"
            DockerURL = "${SWARM_HOST}"
            TLSCACert = "/certs/ca.pem"
            TLSCert = "/certs/cert.pem"
            TLSKey = "/certs/key.pem"
            [[Extensions]]
            Name = "nginx"
            ConfigPath = "/etc/nginx/nginx.conf"
            PidPath = "/etc/nginx/nginx.pid"
            MaxConn = 1024
            Port = 80
    volumes:
        - ucp-node-certs:/certs
    restart: always

**Comment by ekcheu** [comment]
Well, I don't have UCP, but you could just do it the hard way.  You could make a directory on all of your worker hosts that has config.toml and mount that with -v instead of:

interlock-config:/etc/interlock

that way, you don't need a constraint.  Personally I don't start interlock by connecting to the swarm (or even using docker compose), I just log into a worker within the swarm and create interlock/nginx on the local engine and just make sure that the config.toml is configured to connect to the swarm (and yes, interlock and nginx does have to live within the swarm cluster I found out as if it lives outside, nginx.conf won't get updated or restart.  Although in 1.0.1 version of interlock the nginx.conf did get updated even when interlock was outside the swarm cluster oddly enough).
But yes, I'm pretty sure there is a way in compose to use constraints.  I just don't know how to do it.

I'd also either get rid of or modify these lines:

app:
image: ehazlett/docker-demo:latest
ports:
- 8080
labels:
- "interlock.hostname=test"
- "interlock.domain=local"
environment:
- "constraint:node==worker01"


interlock.hostname must match the node where interlock is running  - like worker01  for example, which is where I think you are trying to run it from.  The domain probably must match your real domain as well.  But really you want to start the containers usually via the GUI interface (shipyard for example), or by connecting to the swarm via command line as this command only stands up one container to connect to the backend of nginx.

**Comment by ehazlett** [comment]
You can also use a KV store to centralize the config.  See https://github.com/ehazlett/interlock/blob/master/docs/configuration.md#key-value-store-configuration for details.
