### ISSUE TITLE
shipyard extension install fails with "Tag v1 not found in repository ehazlett/interlock"

### ISSUE THREAD

**Issue by weiner** [ehazlett/interlock#28]
Hello,

it seams that a resent change on the docker registry publication broke the shipyard extension install: 

hier the output of the install.

shipyard cli> shipyard add-extension --url https://raw.githubusercontent.com/shipyard/shipyard-extensions/master/routing/interlock.conf
configuring interlock (https://github.com/ehazlett/interlock for more info)
enter value for container argument -shipyard-url: http://example.deom
enter value for container argument -shipyard-service-key: __KEY_REPLACED__
FATA[0041] error adding extension: Tag v1 not found in repository ehazlett/interlock

**Comment by ehazlett** [comment]
Thanks for reporting!  I'll take a look.

**Comment by ashish235** [comment]
Getting the same error.

**Comment by jacinto123** [comment]
I get the same error. Any chance of getting this resolved?

**Comment by amvapor** [comment]
The v1 tag doesn't exist in the docker hub registry anymore... can be fixed by providing your own conf

`shipyard cli> shipyard add-extension --url https://myhost.example.com/interlock.conf`

and in that interlock.conf change ehazlett/interlock:v1 to ehazlett/interlock:### where ### is a tag that exists at https://registry.hub.docker.com/u/ehazlett/interlock/tags/manage/

for example:
``` json
{
  "name": "interlock",
  "image": "ehazlett/interlock:0.1.0",
  "version": "0.1",
  "author": "ehazlett",
  "description": "application router and load balancer",
  "url": "https://github.com/ehazlett/interlock",
  "config": {
    "prompt_args": [
      "-shipyard-url",
      "-shipyard-service-key"
    ],  
    "cpus": 0.1,
    "memory": 32, 
    "ports": [
      {   
        "proto": "tcp",
        "port": 80, 
        "container_port": 8080
      }   
     ],  
    "deploy_per_engine": false
  }
}
```

this fixes the tag not found issue, but didn't bring the extension up. I've resorted to running interlock as a manually created container in shipyard for the moment

**Comment by jacinto123** [comment]
So then is this project dead?

**Comment by ehazlett** [comment]
Tag has been pushed.  Note that the current development (master) is against swarm.
