### ISSUE TITLE
Cannot start the latest interlock with --swarm-url

### ISSUE THREAD

**Issue by gittycat** [ehazlett/interlock#78]
I'm consistently getting an error about the `--swarm-url` parameter to interlock.
I'm using the latest docker, docker-machine, docker-swarm and interlock (interlock:1.0.0 or interlock:ng)

```
docker run ehazlett/interlock:ng --swarm-url $DOCKER_HOST --swarm-tls-ca-cert=/etc/docker/ca.pem --swarm-tls-cert=/etc/docker/server.pem --swarm-tls-key=/etc/docker/server-key.pem --plugin nginx start
```
results in an incorrect usage followed by this
```
time="2016-02-28T11:02:48Z" level=fatal msg="flag provided but not defined: -swarm-url" 
```
Note the single dash before `swarm-url`.

**Comment by ehazlett** [comment]
Yes as noted in the readme this is a major refactor.  `ehazlett/interlock:latest` still points at the old version for this reason.  If you want to use 1.0+ I strongly suggest looking at the docs (https://github.com/ehazlett/interlock/tree/master/docs) as there are quite a few differences.  First, there is now a configuration file which is why you are getting the error for the flag.  I'm planning to add a migration guide soon but the docs should help in the meantime.  See https://github.com/ehazlett/interlock/blob/master/docs/getting_started.md for a quick start.

Thanks!

**Comment by gittycat** [comment]
Oh, I actually use the config file. I forgot to include the volume in the sample above since I'm normally use a docker compose file. I did double checked and the config file is in `/bin/config.toml` on the container. I use the same config.tom that you list in the nginx example.

So are the `--swarm-xxxx` parameters not passed by parameters to the command anymore? If not, I can't see which new config file entries correspond to them

Also, are the new config parameters case sensitive? They are different between the example in the doc you list and the examples/nginx.
